name: Build and Deploy to Kubernetes

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
          AWS_REGION: us-east-1
      
      - name: Build, tag, push both Flask and MySQL images
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: v1.0
        run: |
          # Build Flask app
            docker build -t $ECR_REGISTRY/webapp-repo:$IMAGE_TAG -f Dockerfile .
            docker push $ECR_REGISTRY/webapp-repo:$IMAGE_TAG

          # Build MySQL with init SQL
          docker build -t $ECR_REGISTRY/mysql-repo:$IMAGE_TAG -f Dockerfile_mysql .
          docker push $ECR_REGISTRY/mysql-repo:$IMAGE_TAG
